version: '3.8'

services:
  nuts:
    image: nats:latest
    container_name: nuts
    ports:
      - "4222:4222"

  publisher:
    build: ./publisher
    container_name: publisher
    depends_on:
      - nuts

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - nuts
